### ISSUE TITLE
pressure not working anymore

### ISSUE THREAD

**Issue by briend** [callaa/Drawpile#171]
I think I was running 0.9.5 before and pressure definitely worked.  Since then I've done some updates for debian sid and I just compiled Drawpile 0.9.7, and cannot get pressure to work at all.  I've tried a Wacom graphire2 and graphire4 tablet to be sure.  Also tested MyPaint, Inkscape, and Krita to be sure my gtk and QT programs worked still.  Is there anything I can run to debug this?  Thanks!  I compiled with debug flags too.. but not sure how to debug anything.

**Comment by callaa** [comment]
Debian Sid comes with Qt 5.3, so the problem was probably introduced by commit b5d99fb, which fixed tablet event handling for Qt 5.4, but apparently broke it for all older versions.
If that is the case, tablets should work fine in the previous commit, 51906e4.

I just tried running the latest version with Qt 5.3 and pressure sensitivity is indeed broken.

**Comment by briend** [comment]
Great!  Boy, and I thought Sid was supposed to be bleeding edge ;-).  Thanks callaa!

**Comment by callaa** [comment]
I got pressure sensitivity with Qt 5.3 working again, at least on my macbook. Can you check out the latest master branch version and try if it works on Debian as well? (Currently the master branch only contains bug fixes and is fully compatible with the latest official release.)

**Comment by briend** [comment]
Bingo!  Fixed.  Thanks Callaa.  Now I can play with the watercolor!!
