### ISSUE TITLE
Suggestions: things id love to see in DrawPile

### ISSUE THREAD

**Issue by EvilKitty3** [callaa/Drawpile#173]
Greetings! Im a user of OpenCanvas1 for at least 9 years and i really love DrawPile. Me and my friend draw alot online together where our drawings practically create almost like animated stories. It is very understandable that this software is still in development but here are few suggestions that id love to see in future DrawPile to have :)

-Polygonal selection tool
it is always super useful to have this tool to select point to point speciffic parts of a drawing like in gimp.
-Transform tool
Having this to manipulate the whole layer or a selection to scale, move and rotate would be a lot more effective than the pasted copy alternative at the moment.
-Temporaly eraser brush
This is what more my two friends complained as they are used to use the back of the tablet pen to erase and then draw again with the pen tip. Personally id also like the eraser to be activated only while the keyboard button is holded down like in toon boom softwares instead of manually selecting tools constantly
-View playback window
When i open a recorded file and for some reason close the playback window, there seem to be no way to reopen it. Would be nice to have that available. Also my friend recently failed few times to open my recorded file versions with the playback window... not sure why
-Better video export
I was fiddling with this feature but cant help but to thing it doesnt create good quality videos. The exported video has low quality, is picky with in what player it plays and the white bg turns yellow. I alternatively export the images and put together in blenders video editor but it would be nice if DrawPile would get a more improved and easier video export without all the additional setups with paths n stuff. Still, as much this is the least of an issue i think its worth to mention but i love the idea that it does try to have this feature :D

 This is pretty much all that i think that drawpile still needs to be the perfect collaborative drawing software.

**Comment by callaa** [comment]
Hi, and thanks for your interest!

**Polygon select + transform**  
Pasted selections can be resized at the moment, and I've been planning on adding a rotation mode too. Currently, it has been a bit difficult, since the selection is always rectangular, but adding support for polygonal selections might, as a side effect, make rotation easier to implement too. This one goes to the TODO list :memo:.

**Temporary eraser**  
Using the tablet eraser should work, but it has been buggy in the past. (#152) It currently seems to work, at least for me, on Linux and OSX.
How does the eraser button work in Toon Boom?

**Playback**
At the moment it does seem to be fairly easy to close the window accidentally. Adding a "really close?" confirmation dialog if the playback isn't fully finished yet, would be an easy fix, but dialog boxes are really annoying and should be avoided if possible. A "reopen the playback window you just closed" button would be the best solution.

As for unopenable recordings, I have no idea. The program should display an error message if it is unable to open the file.

**Video export**
Which format were you exporting to, and which quality setting? I seem to recall seeing something like this when the quality settings were too low.

Unfortunately, I can't think of any way to make setting up video export easier. For users, the easiest way would be to include ffmpeg in the package, but in many countries (like the USA) that would actually be illegal due to patent license issues.

**Comment by EvilKitty3** [comment]
hm cant remember the settings i used for the video exporter right now but if you could suggest one that makes the video look good id be happy to try. They also use as thirdparty software quick time player to export and play videos. Not sure if that sounds anything much informative though.
ToonBoom has this feature to temporaly select a tool. For example when i hold down the E button, the eraser is selected and ready to use but once i release the E button then it inmediately returns to the previous tool that i was using like the brush button for example instead of manually selecting the previous tool again. Its a small feature i enjoy using all the time in ToonBoom Harmony for projects.

**Comment by callaa** [comment]
The temporary tool selection sounded so handy I decided to implement it right away :) In addition to the tools, it also works with tool slots (keys 1-5.) I had to work around Qt's normal shortcut system a little, since it isn't really designed to work this way, so it only works with single key shortcuts. This isn't a problem for the default tool shortcuts though, since they all use just a single key.

**Comment by inesmyuu** [comment]
Hello! I've also been using Open Canvas for many years, but the network stopped working with me for a while now, so I'm very happy with Drawpile. I've tried it and it works perfectly well! (after an headache to try it and make the host/join part work. I was only able to make it work using Hamachi. Basically letting my friend enter the Hamachi netwrok, and only then letting him join in Drawpile).

To add new things (that haven't been said here)

-Maybe a navigation window with the zoom in and zoom out in it too

-Canvas Flip horizontally and vertically options (it's very useful to flip during drawing, it helps with proportions)

-Better brush options, The lower opacity works a bit bad in painting and also the pressure color option is a bit too strong. I've used very limited drawing tools in the past, and even java painting where I could paint well with their low opacity and such, here I can't. It's a bit tricky :)
Also, hope that in the future we can have some more brushes (or a way to import brushes from other open source software maybe?)

This is all I can think for now... I can't wait to try it out with more friends!

**Comment by callaa** [comment]
>(after an headache to try it and make the host/join part work. I was only able to make it work using Hamachi. Basically letting my friend enter the Hamachi network, and only then letting him join in Drawpile).

Getting the connections working can unfortunately be really difficult. Hopefully IPv6 will someday become available for everyone and things will get easier.
One of the things I want to do for Drawpile 2.0 is a new improved dedicated server that should make setting up public servers easier, which would bypass the usual connection problems.

>To add new things (that haven't been said here)
>
>-Maybe a navigation window with the zoom in and zoom out in it too

The navigator window actually had zoom buttons, but I took them out because I thought there were too many of them already :cold_sweat: Since the navigator can be used to pan the view by clicking/dragging, perhaps zooming with the mouse wheel might be a good addition.

>-Canvas Flip horizontally and vertically options (it's very useful to flip during drawing, it helps with proportions)

This is a good idea, and should be pretty easy to implement too, I think.

>-Better brush options, The lower opacity works a bit bad in painting and also the pressure color option is a bit too strong. I've used very limited drawing tools in the past, and even java painting where I could paint well with their low opacity and such, here I can't. It's a bit tricky :)

Have you tried toggling the indirect/incremental drawing mode? (The button next to the mode dropdown box. It seems to be very easy to overlook, I'll have to think of something to make it stand out better.) It should help with low opacity painting. If the brush strokes still look bad, can you take a screenshot?

The pressure sensitive color mode fades the color between the current foreground and background. You can try selecting a background color that is closer to the foreground to make it less strong. (Right click on the brush preview to select colors, or press X to swap foreground and background)

>Also, hope that in the future we can have some more brushes (or a way to import brushes from other open source software maybe?)

This is something I would like to do in the future. It might be possible to integrate MyPaint's brush engine with Drawpile, or at least a part of it.

**Comment by inesmyuu** [comment]
-Ok, zooming with the mouse wheel is good! :)

-Hope the flip is easy, it's really great for drawing!

-I'm going to try mess more with the brushes and see if I can use them better or see if there is a better way to explain the problem. I guess I need to try them out more. If anything, I'll take a screenshot like you suggested

And again, thanks :D

**Comment by callaa** [comment]
Thanks everyone for the ideas! The new version is now out and most of the features here have been implemented, so I'm closing this issue. Feel free to open new ones if you have more suggestions!
