### ISSUE TITLE
Cursor Offset with Tablets

### ISSUE THREAD

**Issue by tchan5158** [callaa/Drawpile#177]
Two of my friends and I experienced this with our tablets.  We are using Windows 7, Wacom cintiq, and Genius.  This is with the latest version 0.9.8.

The crosshair and the brush circle is supposed to line up in the center, but the moment we press down to draw, the circle moves to the bottom right by a few millimeters.  about this much:  | |

My friend with the Genius tablet had very scribbly lines under the default smoothing.  He had to raise smoothing all the way to the right side to be able to make any decent line.

My friend and I are able to fix the offset by disabling our tablet driver and re-enabling it, but we lose our pressure sensitivity.  My friend with the Genius tablet can NOT fix it no matter what we tried.  :(

Since a screenshot doesn't show the crosshair, I drew one as precise as I could.  Image attached.

Included also is the Scribbly Line at default smoothness, drawn with Genius tablet.

Thanks for looking into this :)  Other than these issues, I enjoyed this program :D

![drawpilecursor](https://cloud.githubusercontent.com/assets/11186489/6364209/7b94c65a-bc68-11e4-9ab0-dcc0bbe2de79.jpg)

![drawpilescribbe](https://cloud.githubusercontent.com/assets/11186489/6364332/c0ebc234-bc69-11e4-91a1-1fdbf4f0a837.jpg)

**Comment by callaa** [comment]
Thank you for the report. Right now my ability to debug tablet problems is unfortunately fairly limited, since I only own one (an old wacom bamboo), but I'll prepare a new version of my tablet test program that might help determine whether the bug is in Drawpile itself or the Qt library. 

If you disable tablet events from the preferences dialog, does the jitter and offset still happen?

**Comment by tchan5158** [comment]
Oh thank you!  Disabling tablet feature worked for all three of us.  I'd choose drawing accurately and smoothly over having pressure and offset any day.  :)

We'll wait for your next release :D

**Comment by callaa** [comment]
Good to hear disabling the tablet feature worked. This actually gives me an idea. Since the tablet event sometimes delivers invalid coordinates, but mouse events work fine and the pressure value is (presumably) OK, it might be possible to combine the two so the pressure is grabbed from the tablet event but the pointer coordinates are got from the mouse event. I'll try if this works and will include it in the next release if it does.
