### ISSUE TITLE
NAT traversal

### ISSUE THREAD

**Issue by Tirifto** [callaa/Drawpile#182]
I have tried to use Drawpile with other people, but it didn't work because we couldn't connect to each other. I came to understand that this is most likely due to us being ordinary users behind a NAT. While the website does provide info on how to deal with this, no solution is convenient. 

Average computer user does not have a server available and won't be able to forward his ports due to lack of technical knowledge or not being able to modify the router settings.

I think that Drawpile should eventually be able to deal with this and allow users to connect to each other in a simple way without requiring them to tinker with various programs and devices to make it work. The Tox project is an example of this. It aims to be a simple and secure communication client and usually works out of the box, no need to forward anything. ( https://github.com/irungentoo/toxcore )

Perhaps some Tox code could be used in Drawpile? Or some other software? However it's done, I believe it needs to be done. It will be an important step that will open Drawpile to masses of people.

**Comment by callaa** [comment]
NAT firewalls are indeed a big problem. Unfortunately, NAT hole punching for TCP is much more difficult and less reliable than for UDP. (Tox uses UDP for this reason.) UPnP could be used to automatically set up redirects for home routers, but this won't work if the user's router doesn't support UPnP or the user is behind carrier-grade NAT (which is difficult to traverse with any method.)

To alleviate this problem a little, I'm planning on setting up a public server for people to use in the near future. This isn't a perfect solution, since I may run in to server capacity issues if the service becomes too popular. For version 2.0, I have planned some protocol changes which should make setting up servers easier and more secure. (One of the planned features is end-to-end encryption so the hosting server doesn't even have to be fully trusted.)

I'm still hoping IPv6 will become widely available someday and NATs will be a thing of the past.

**Comment by Tirifto** [comment]
I've heard all sorts of things about UPnP, but as long as it works, sure.

As for the public server, how would that work? Access to a public server, or even better, multiple public servers is nice. Wouldn't that, however, put all the users who connect to the server on the same canvas? Drawing with random people can be fun, but that still won't fix the issue, seeing as some people, including me, would like to share a private canvas with a friend or two.

As for the hole punching, can't Drawpile also use UDP? I don't know how difficult it is to implement, but would it be possible to add UDP as an option or a fallback? While I also hope for a rapid growth of IPv6, it would be nice to find another solution before that dream becomes reality.

I had this problem with more programs, so I searched for a solution a while back. I found some VPNs, but none were simple and straightforward. I used Hamachi a long time ago, but being proprietary and centralized makes it a horrible solution. I came across a program called "n2n". From what I've read, it connects two computers with the help of a third server, but once connected, the two compuers can communicate on their own. If it works this way and can be implemented in Drawpile, then perhaps it could just use the public server to connect two people and let them have fun. This would also solve the bandwith issues.

I also found a program which claimed to allow NAT to NAT communication without any port forwarding or servers, but I forgot it's name and I couldn't find it afterwards. I think it was also in Arch User Repository, though.

**Comment by callaa** [comment]
> As for the public server, how would that work?

The standalone server can host multiple separate sessions. The sessions can also be password protected. The downside at the moment is that users must trust the server not to eavesdrop on them, if privacy is a concern. This will be (mostly) fixed by the protocol encryption I've planned for the next major version.

> As for the hole punching, can't Drawpile also use UDP?

Technically yes, but I would have to implement a TCP-like reliable messaging protocol on top of UDP (in addition to the hole punching logic, which usually needs an external server to facilitate the traversal), which is way too much work for me right now.

Using VPN software such as Hamachi or n2n (that one was new to me, I'll have to take a closer look) is probably the easiest way to work around the NAT problem right now.

**Comment by Tirifto** [comment]
I am not sure if this will help, but I was reading news and came across a protocol called QUIC: https://en.wikipedia.org/wiki/QUIC

**Comment by Tirifto** [comment]
> I also found a program which claimed to allow NAT to NAT communication without any port forwarding or servers, but I forgot it's name and I couldn't find it afterwards. I think it was also in Arch User Repository, though.

I accidentally found it while reading something! The program is called pwnat, homepage is here: http://samy.pl/pwnat/

How about this, n2n, QUIC or uPnP? Any plans for any of those?

**Comment by callaa** [comment]
I found [libupnp](http://pupnp.sourceforge.net/), which is used by software such as ktorrent to automatically set up port forwardings. Unfortunately, it seems this library is quite difficult to get working in Windows. There is also GUPnP, but that depends on GObject and so would also be difficult to use on Windows and OSX.

**Comment by Tirifto** [comment]
@callaa I found [MiniUPnP](http://miniupnp.tuxfamily.org/), in a pull request for toxcore. Could that perhaps be easier to get working in other systems?

**Comment by callaa** [comment]
@Tirifto MiniUPnP looks very promising! I managed to compile the library on Windows, so I'll try implementing the port forwarding functionality next.

**Comment by callaa** [comment]
Success! Automatic port forwarding now works on Linux, OSX and Windows. (commit 29ed264)
Drawpile now even automatically fetches the public IP address from the router after setting up forwarding.

**Comment by Tirifto** [comment]
-highfive-
