### ISSUE TITLE
Suggestion: Layer names. Do not call the layers "New layer" 

### ISSUE THREAD

**Issue by horkana** [callaa/Drawpile#185]
Drawpile has two default layers, Background and Foreground. 
If you use the layers dialog to add another layer it gets called "New layer" "New layer 1" New layer 2" etc. 

I would strongly encourage you to not include the word "New" in the layer label. As soon as you create the layer it is no longer "new" and the extra word new is not a particularly helpful label for users. I'd suggest using just the word "Layer"

The numbering seems a little strange to me too. Images already have 2 layers by default, but if you add extra layers what Drawpile calls "New layer 1" by default is actually the 4th layer. 

After Background and Foreground I'd suggest the next (i.e. 3rd) layer be called "Layer 1"

**Comment by callaa** [comment]
This sounds like a more sensible naming scheme. The numbering is now implemented so the suffix is always +1 of the biggest suffix number (of layers with the same base name.) This way, if we create layers "Layer 1", "Layer 2" and "Layer 3", then delete "Layer 2", the newly created layer will be "Layer 4" instead of "Layer 2" again.

**Comment by horkana** [comment]
Max plus one is a clever solution, I like that. 
Thanks.
