### ISSUE TITLE
One small feature request for the selection pls

### ISSUE THREAD

**Issue by EvilKitty3** [callaa/Drawpile#190]
Hello again! I must say drawpile has evolved super great!  The new features enchanced the drawing experience with friends amazingly. There is just one more thing id love to request if posible.
Currently i can only manipulate a drawing when pasted. What i would like to see is having the process of copy>delete>paste of a selection faster with just hitting enter after creating a selection to get to the point where i can move and manipulate the selected drawing. Would that be posible or is there already something similar implemented for a quicker way to transform a drawing?

**Comment by callaa** [comment]
You can shorten the process by one action by using Cut, which is the same thing as Copy>Delete.
However, even so the process could indeed be a little easier.
Perhaps dragging a selection after it has been made should automatically trigger cut&paste.

**Comment by blurymind** [comment]
cutting and pasting does not paste the image in the same place that it was copied from.

A more useful default behavior would be to remember the original location and paste in it.

**Comment by callaa** [comment]
An image will be pasted to its original location as long as the old selection exists. (Or rather, the image will be centered on the active selection, which means over the original location if the selection hasn't been moved.) If there is no selection, the pasted image will be pasted at the center of the viewport. I think this behaviour is more intuitive, since the image will never appear offscreen, unless explicitly hinted with the selection.

**Comment by callaa** [comment]
Moving, scaling or rotating a selection will now automatically transform the image content too, without needing a cut&paste operation. If someone wants the old behavior (transforming just the selection), I can add an option to toggle between the two modes.

**Comment by benrob0329** [comment]
This seems to be broken now, is there an option that needs to be set? Transformed selections seem to "snap" back to their old position.
