### ISSUE TITLE
hibernated sessions don't re-register with announce list after restart

### ISSUE THREAD

**Issue by briend** [callaa/Drawpile#192]
It seems that if my server restarts and the sessions are restored from hibernation, they are not announced on the public server list, and/or they disappear after a few minutes.  I can connect to them manually still.
this is my script:

/usr/bin/drawpile-srv --hibernation /home/drawpile/sessions --hibernate-all --auto-hibernate --history-limit 100 --persistent --sessions 5  

version 0.9.9

**Comment by callaa** [comment]
Right now, the announcement info is not stored in the hibernation file so the server can't automatically reannounce it. When autohibernation is used (i.e. the session is hibernated but the server can still be running,) it would also be desirable to maintain the announcement since the session is still available for joining. However, this gets a bit complicated when socket activation is used, since the entire server can be shut down but will automatically restart on demand. In this case, I can't think of any way to maintain the announcement.

Until I can come up with a proper solution, I think the simplest workaround is to just disable autohibernation when hosting long running sessions.

**Comment by callaa** [comment]
It's taken a while, but this now works in the current master branch!
