### ISSUE TITLE
Free-form selection move removes pixels, but doesn't put them back

### ISSUE THREAD

**Issue by GreenReaper** [callaa/Drawpile#195]
If I move a rectangular selection, the pixels on that layer inside the selection end up at the place I moved it to. If I move a free-form selection, they don't - they just disappear. Windows, 0.9.10.

**Comment by callaa** [comment]
I can't believe I missed this. Currently, only selection polygons with four vertices (transformed rectangles) can hold pasted images, since the image's transformation matrix is generated from the vertices. As a simple fix, a freeform selection is now automatically converted to a rectangular selection when an image is assigned to it.
