### ISSUE TITLE
Joining via drawpile:// url and recording

### ISSUE THREAD

**Issue by pachuco** [callaa/Drawpile#230]
When joining via URL, say drawpile://drawpile.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
I can't help but notice that I'm thrown directly into the session without chance to start recording.

I am able to get around this by joining session, grabbing IP from network monitor and exiting.
Then I join session through the acquired IP and go into the appropriate room myself, with recording on.

**Comment by callaa** [comment]
This is from clicking on an URL, right?
The address box in the join dialog also URLs, so you can also copy&paste the URL there.
Perhaps rather than joining automatically, the join dialog should be shown even when launching from an URL. This way, you can also change your nickname before joining, if necessary.

**Comment by callaa** [comment]
I changed it to display the join dialog before actually joining. I'm releasing the new version later today, so this fix got in just in the nick of time :)
