### ISSUE TITLE
Pressure Glitch

### ISSUE THREAD

**Issue by akunim** [callaa/Drawpile#233]
When first touching the pen to the tablet, I'll often get a large pressure spike, which results in lines that start with big dots, like in the image below.
![ss 2015-08-09 at 09 53 25](https://cloud.githubusercontent.com/assets/2343421/9155399/cde7bcf0-3e7c-11e5-9d4f-f699cdff8051.png)
I've only started experiencing this as of 1.0.1, but another user has reported having a similar issue since 1.0.0.
Here's a .dprec of the attached image [http://ftp.caturday.party/pressureGlitch.dprec](http://ftp.caturday.party/pressureGlitch.dprec)

**Comment by callaa** [comment]
Does enabling the bug workaround mode in the settings dialog have any effect on the glitch?

**Comment by akunim** [comment]
Negative. That recording was made with the bug workaround enabled.

**Comment by callaa** [comment]
Do you get the same kind of glitch with the workaround mode turned off? Looking at the recording, the values look very much like bad data received from the driver, rather than something that happens inside Drawpile.

**Comment by akunim** [comment]
That's possible -- I know that the tablet I'm using historically has some quirkiness with drivers (Huion H610).

I do still experience the dots with the workarounds turned off, and I don't get the dots when using GIMP or FireAlpaca. I wonder if they have some kind of debouncing built in? 

I'll try reinstalling my drivers and see if that has any effect.

**Comment by callaa** [comment]
Most likely the problem is in Qt. It has some weird quirks when in comes to tablet events, and the quirks seem to be different on every platform. Once Krita has been ported to Qt5, I'll take a look at how they solved it. (I think right now Krita uses custom platform specific code to get the tablet events.)

**Comment by tembrook** [comment]
I have the same problem with the same brand of tablet. No other program has this problem. Has anyone come up with a solution?

**Comment by PhilipWitte** [comment]
I have this same problem. I have a Wacom Intuos 4 and I use Manjaro Linux (kernel 4.1, Xfce + Compton). So it's not related to Huion tablets or anything.

Was talking to a couple other users about it and apparently it doesn't happen for a guy running Ubuntu 15.04 but happens for someone else (albeit in a slightly different way) running Windows Vista.

**Comment by KurinPawpad** [comment]
Same problem here, Archlinux, installed from AUR. ldd contents here: http://pastebin.com/Qcf0bteg

**Comment by callaa** [comment]
KurinPawpad: Since you're using Arch, can you try the latest stable-1.x branch version? I discovered that sometimes the application is delivered two events for the tablet press (tablet press + mouse press) and added some code to ignore the other event when that happens.

**Comment by KurinPawpad** [comment]
calaa: Changing to the stable-1.x branch fixed another issue (namely the one where it acts like you're holding shift to get a straight line after undoing a line), but not the above-described issue.  Still getting initial full-pressure on tablet down events.  I have attempted to toggle off the bug workaround option, but that breaks pen pressure entirely (blobby and uneven, almost no pressure even with a sharp curve in the tablet control).  Using a Cintiq 13HD

**Comment by PhilipWitte** [comment]
@callaa I'm on Manjaro but I'm also using DrawPile from the AUR (v1.0.1). For me the "blob" (full-pressure dot) happens with and without Bug Workarounds. However I just noticed that with Bug Workarounds ON the 'blob' is part of the stroke (eg, hitting ctrl-z to 'undo' will remove the entire line including the blob) while with them OFF the 'blob' is counted as a separate stroke (eg, you have to 'undo' twice.. first 'undo' removes the line, second removes the blob).

**Comment by KurinPawpad** [comment]
After doing some testing again, I can safely say that it is not linked to the actual pressure seen by the stylus, since changing the pressure curve does not change the size of the dot.  Drawpile doesn't see the first segment of the line as from the tablet pen at all.  I tried changing the pressure curve to zero/flat (lower left to lower right) and it's still full size/100% size as if I'd used a mouse.

**Comment by KurinPawpad** [comment]
Doing some more testing with QTabletTester, and got 

3695: mouse pressed at 264, 308, buttons=[Left]
3695: stylus (pen) pressed at 264.2, 308.7, pressure=15.3%
3698: stylus (pen) moved at 264.2, 308.5, pressure=15.3%
...
4421: stylus (pen) moved at 365.4, 339.1, pressure=0.0%
4421: mouse released at 365, 339, buttons=[]
4421: stylus (pen) lifted at 365.4, 339.1, pressure=0.0%

(Shortened for clarity)

So Qt is definitely seeing separate pen and mouse down events, which is likely what's causing that initial pressure spike.

**Comment by KurinPawpad** [comment]
If you were to toss the initial mouse-down event's pressure and locational data, and using the initial 'move' event as the starting location and pressure instead, that may fix the issue.  If the two events are in fact in different places, it would be a fraction of a pixel if anything.

**Comment by callaa** [comment]
That's a good idea. However, simply ignoring the PenDown event will make it impossible to do single point dabs, so perhaps instead I should save the first point, then generate the PenMove for it when the pen is actually moved, using the pressure from the move event. For single point dabs, the penmove can be generated on PenUp event, if the pen didn't move.

The underlying problem seems to be that Qt is generating and sending a mouse event *before* the tablet event, so Drawpile thinks its in mouse mode. I think this is a regression in Qt, since it didn't use to do that. (Or else it has always been random and I've just been lucky so far.)

Now that I think about it, another option would be to defer sending the PenMove action until the mouse/stylus has actually moved or been lifted. Then there would be time to decide whether it was really a pen or a mouse that triggered the event.

**Comment by KurinPawpad** [comment]
Ignoring pen-down events wouldn't make it impossible to do single point dabs, because single-point dabs aren't single points.  Even a slight bump isn't a single event.  It's next to impossible to get one frame events using a tablet, there's just too much resolution to them.  Defering the event may also work, though.

**Comment by callaa** [comment]
Yes, with tablets that's true but with a mouse it's very easy to keep it still.

I just pushed a commit that implements the fix. It works on my computer at least. Does it fix it for you too?

**Comment by KurinPawpad** [comment]
Compiled the newest commit and that seems to have fixed the problem, but another problem seems to have shown up, as well.  Occasionally (about 1 in every 10-20), while 'Enable bug workarounds' is enabled, the first dot of the pen stroke is full pressure.  Turning 'Enable bug workarounds' off clears this up though, and you don't get any first-dot pressure bug, that I can tell.

**Comment by callaa** [comment]
That was caused by bad pressure data in the tabletpress event, which got used when drawing single point dabs. (Looks like they're possible even with the tablet after all!) So, I just ignore the dabs made with a tablet since the pressure value can't be trusted.

I think this bug can be considered solved now, but if you find any more glitches, please comment :) Thank you for your help, I didn't think I was going to be able to fix this one!
