### ISSUE TITLE
Drawpile Crashes After Joining a Session

### ISSUE THREAD

**Issue by Squeebs** [callaa/Drawpile#234]
My friend who lives in Canada (I'm in the US) recently downloaded and installed Drawpile and I had created a password-protected room for them to join. When they tried joining, it kept saying "Connection Timed Out", so I told them to create a password-protected room, and when I joined, I found that there was no canvas to draw on, and instead of my user name, I was "User #2". Finding this a bit odd, I waited for a bit, and all of a sudden, my computer told me that there was an error and Drawpile stopped working. I reopened the program and rejoined my friend's room, and the same thing happened, and I was "User #3". After a few minutes, I was again kicked from the program. I had them recreate the room, same thing began happening. I told them to close and reopen Drawpile, but that didn't fix the problem. I'm thinking this could very well be a server problem, but I might as well post the problem here just in case it's not.

**Comment by callaa** [comment]
It seems the login phase goes through correctly, since you get a user ID. (They are assigned sequentially and not reused until the counter wraps around, which is why you get 2 followed by 3.)
However, since you see the user number rather than name (and no canvas), it seems the actual session content is never transmitted. One reason for this could be that the initial state from the hosting user hasn't been uploaded or marked as finished. If you can generate a crash report (like in issue #232), it would be very helpful. (I don't use Windows much myself, so I don't know how this is actually done.)

Some things to try:
- Try hosting on the public server. If the same thing happens there, mark the time (and timezone) and I'll look at the server logs to see if there are any clues
- Try running hosting with drawpile-srv (this is in the same directory as drawpile.exe, typically c:/program files/drawpile) rather than the built-in server. You can give it the parameter "-V" to have it print out extra debugging information.

**Comment by Squeebs** [comment]
I think it was just a server thing; it began working correctly about a half-hour later. I didn't have time to post an update here because I had to go out. Thanks for the suggestions though; if it happens again, I'll generate the crash report and post it.
