### ISSUE TITLE
"Connection Timed Out"

### ISSUE THREAD

**Issue by probablyjasper** [callaa/Drawpile#237]
whenever i try to connect to a server hosted by my friend, i get an error that says:
could not connect to server
connection timed out

**Comment by callaa** [comment]
This is most likely caused by a firewall.
Some things to try:

Is the hosting user behind a NAT? Drawpile can set up port forwarding automatically if UPnP is enabled on the router. If it works, the internal IP (typically starting with 192. or 10.) in the status bar will change into the public IP a few seconds after starting the session.
Additionally, Windows firewall, or any third party firewalls (e.g. McAfee) may be blocking the port (27750 by default.)
