### ISSUE TITLE
Feature Request: Protocol over p2p conmmunication

### ISSUE THREAD

**Issue by hacker-owl** [callaa/Drawpile#297]
As I am encontering problems with connection to my friend's personal computer, I wonder if it is possible to build drawpile's protocol over p2p communication? As IPv6 is still not supported everywhere, and IPv4 access in many cases are not possible for personal computers. Adding p2p features will also enable user to have a static random string as their identity instead of constantly changing IP numbers. However, I don't quite understand how these protocols work within drawpile, if you think this request make no sence at all, fell free to close it.

**Comment by callaa** [comment]
I'm afraid P2P would not help in this case since, as the name implies, it involves direct connections between peers. Even services like Skype (when it was P2P) used servers (supernodes) to work around the NAT/firewall problem.

However, a true P2P protocol without a central server would be a cool feature to have, but it would require a substantial redesign of the protocol. Without a central server to dictate the official serialization of drawing commands, keeping all the nodes synchronized is no longer trivial. 

The P2P protocol would have to solve at least the following problems:

 * Initial peer discovery (could use an announcement server like now)
 * How to ensure consistent serialization?
 * What kind of network topology?
 * How to deal with netsplits?

The P2P model is much more complicated, but it has a couple of advantages over the client-server model: bandwith costs are distributed and the problem of server/hosting user dropping out does not exist.

Disadvantages are additional complexity, firewall troubles, increased latency (depending on the network shape) and the possibility of netsplits.

Weighing the pros and cons, I don't think P2P is a good architectural fit for this application. It's a very interesting problem to think about, though, so thank you for the suggestion! It may even be possible to incorporate some P2P inspired ideas to the current model. For example, by supporting live migration of sessions to another server, a session could survive the loss of the hosting server. Another advantage of the P2P model could be had by using multiple connected servers in a tree hierarchy to support more simultaneous users.

**Comment by hacker-owl** [comment]
Well your thinking is much more advanced than mine. This is what I originally thought, this may answer some of the problem that you have mentioned with p2p, but I do not think this is a good solution.

- peer discovery
    
    using an exsting p2p libraries, e.g. libtox used by tox chat or libtorrent used by bit torrent tracker.
    as they are existing libraries and there are already numerous of servers.

- consistent serialization

    I don't quite understand the consistent serialization you have mentioned here, according to my
    knowledge, this is done by heart beat data pack, but possibly we are not talking about the same 
    thing

- network topology and netsplits

    this is where I haven't gone detail into. But with regarding to the original purporse, I would say a
    pseudo servermodel, that is all peers connect one peer, which is selected. This makes no difference 
    with a server client model, but the point is the server can be hidden under a local net work or a
    router, and easily be found by other clients with out any extra configuration on IPv6 or NAT.

**Comment by schoerg** [comment]
P2P is not much different than the current approach. Either one of you needs to be connectable from the outside. If this is not the case and help from a server is needed, then you could just run the Drawpile server on that machine and you won't have the problem anymore.

**Comment by callaa** [comment]
By consistent serialization I mean how to ensure each node gets the exact same session history with all the drawing commands in the same order. With a central server this is easy: the server just distributes the commands to every client in the same order. But in a P2P mesh, there is no one node that can decide the order, so something more advanced (like vector clocks) must be used to get the nodes to eventually agree on a consistent ordering.

The pseudo server model you propose might be workable. It sounds like the same thing I was thinking with session migration. However, while it can rescue sessions when the original host leaves, it won't help with the NAT problem. NAT and P2P just don't play well together.
