### ISSUE TITLE
Creating sessions from dedicated server directly

### ISSUE THREAD

**Issue by pachuco** [callaa/Drawpile#307]
It would be great to be able to create sessions directly by dedicated server with all params set in place, via session config file.
Params like name, canvas size, layer names and lock status, welcome message and some form of authorization for moderators.

My current workflow for dedicated server is: start dedicated with config file, start drawpile and configure session, adjust layers and canvas, close drawpile, power outage, start over again.
Not very practical for self-reliant servers.

Possible caveat: the ID-based authorization system.

**Comment by callaa** [comment]
The current session hibernation feature could be extended to handle session "templates" as well. Basically, the server would ensure certain sessions are always active and reload them from file when they are not. The authorization stuff can be done by setting up a moderator account.

**Comment by callaa** [comment]
This is now implemented. Turned out to be quite a simple change. With the new server, you can now create session templates, which are essentially hibernated sessions that are not removed when activated. The template is hidden when there is an active instance of it (even a hibernated one,) but when the session ends, the template becomes visible again.

The template can be created in two ways: writing it out manually in dptxt format (like the ones in the tests/ directory) or by hibernating a session and using it as the base. The template file is just a regular hibernation file, but with the extension ".dptpl".

**Comment by pachuco** [comment]
I'd like to add to this the ability to start server from .dprec
