### ISSUE TITLE
Root CA certificate is not Trusted

### ISSUE THREAD

**Issue by ZeeMBee** [callaa/Drawpile#353]
I have tried several ways to fix the problem of me not being able to join any servers and nothing works so far 

![image](https://cloud.githubusercontent.com/assets/21091159/17755819/4a0f078a-64aa-11e6-8b12-496d19c73456.png)

**Comment by callaa** [comment]
This is an SSL error, so most sessions hosted somewhere else than drawpile.net's public server should work. Did this problem appear when you updated Drawpile or did it just start on its own?

**Comment by ZeeMBee** [comment]
It started happening on its own

**Comment by Luqiol** [comment]
My friend who runs a Mac also has this same issue. I've tried to set up a private session but it never connects. Drawpile.net's public server was perfect. My friend tried to find the SSL certificate to trust drawpile.net but cannot. Is there another way to work around this?

**Comment by callaa** [comment]
I managed to reproduce the problem myself now. Looks like this same problem affects many other Qt based projects on OSX as well, so it was probably caused by some change in a recent OS update.

I added a workaround that simply ignores the error on OSX. I'm not sure if this is the proper way to fix it, but at least it works. I updated the OSX build: https://drawpile.net/files/osx/Drawpile%201.0.4-2.dmg
