### ISSUE TITLE
Fill Selection Overlap 

### ISSUE THREAD

**Issue by shadowcopalypse** [callaa/Drawpile#372]
When filling a selection over another selection there's a white rectangle leftover.  Linux Manjaro 

![selectfill](https://cloud.githubusercontent.com/assets/17581036/20060288/8554b142-a4c8-11e6-9760-398693819456.gif)

**Comment by callaa** [comment]
Thanks for reporting and sorry it took me so long to respond.

Looks like this bug has been present ever since the area fill feature was added. The fill command used the REPLACE blend mode, which worked fine for rectangular fills, but obviously not for freeform selections. I can't believe I missed it!
The fix is now in the stable branch and will be in the soon-to-be-released 1.0.6 version.
