### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Derpcatthing** [callaa/Drawpile#381]
I woke up to find drawpile says my IP address is banned when I connect to a server.
could someone explain why my IP address it banned for?

**Comment by callaa** [comment]
According to the server logs, you've been kicked a total of 6 times in the past 48 hours. Being kicked multiple times in a short time triggers an automatic ban.

**Comment by Derpcatthing** [comment]
well the server i tried to connect to earlier did keep kicking me while i was connecting :/

**Comment by Derpcatthing** [comment]
just another Question are we allowed to Report servers?

**Comment by Derpcatthing** [comment]
the people of that server didn't listen to what i said about kicking 6 times is a ban

**Comment by Derpcatthing** [comment]
the person who owns this server is called BB

**Comment by callaa** [comment]
I just finished reviewing the session that got you banned. Chat messages are not recorded, so I don't have the context, but looking at the drawing activity, it seems you were having a quite prolonged argument with a session operator. Five other operators apparently agreed, since you were kicked by them as well after attempting to rejoin the session. Without knowing what was said in the chat, I can't tell whether they were being unreasonable, I'll give you the benefit of the doubt and remove the ban.

However, I would advice against attempting to rejoin a session from which you have been kicked. If the operators don't want you there, that's their prerogative.
