### ISSUE TITLE
Docks

### ISSUE THREAD

**Issue by bluekittyyoyo** [callaa/Drawpile#386]
I have run into a problem where if you drag out a dock and put it back, if it is the topmost dock other than tool settings, it will be covered up by the tool settings. I have tried to fix this by deselecting and re-selecting all docks, uninstalling and reinstalling Drawpile, and installing Drawpile again with uninstalling, and the problems persists. Help would be greatly appreciated, as I am getting extremely frustrated because this prevents me from drawing comfortably in the program.
![image](https://cloud.githubusercontent.com/assets/24984376/21747563/6e70c620-d527-11e6-920f-e4b8ed45bbc7.png)
(colour and layers selected)

![image](https://cloud.githubusercontent.com/assets/24984376/21747576/a9054c0c-d527-11e6-88fd-d1ce437dace6.png)
(colour, layers, and tool settings selected)

![image](https://cloud.githubusercontent.com/assets/24984376/21747582/e1ab18b6-d527-11e6-8e51-4e37c12caebd.png)
(colour, layers, and tool settings selected continued)

**Comment by callaa** [comment]
Looks like the brush panel is floating above the others. Try dragging it from the header button bar, it should slot back in.

**Comment by bluekittyyoyo** [comment]
Thank you for replying! Eventually I came to realize that is acting as its own separate entity, but I cannot drag it at all. The only way to move it is to resize it in one direction until it is in the place you want it to be.

**Comment by callaa** [comment]
Other users have also reported the problem where the brush dock can't be moved at all. I haven't been able to reproduce the bug myself, so it seems it only affects some computers.
There is a new option in the View->Docks menu for locking the docks in place. Try if locking and unlocking has any effect.

If all else fails, you can erase Drawpile's registery keys (specifically the window/state key.) This should reset the docks to their initial layout.

In any case, I think the source of the problem is the brush dock's custom header. Apparently it just doesn't work right on some platforms. I'll have to redesign it in some later version.

**Comment by bluekittyyoyo** [comment]
Thank you again for responding. Locking and unlocking the docks did not work, but deleting the registry did. Thank you so much for your time on this!
