### ISSUE TITLE
Hibernated session not keeping persistence

### ISSUE THREAD

**Issue by jameslis** [callaa/Drawpile#394]
We create a persistent session on a dedicated server that goes into hibernation after some inactivity.
When a user logs in and it comes back up, it will be deleted right away _if_ that user logs out quickly.

If the user draws for a some time then leaves, the session seems to work as intended: the session will persist and hibernate.

As a temporary workaround (we are using 1.0.6 dedicated server): 
Is there a way to disable auto deletion of sessions? 
Maybe there's some config option I can use to extend the lifetime of a session or something like that? (Otherwise, I am able to recompile the code if the solution is somewhere in there.)

We are running with auto-hibernate, hibernate and -P flags already and this is still happening. We host long running sessions on our server that people use throughout the course of a week.

Thanks

**Comment by callaa** [comment]
The session hibernation system is much improved in the 2.0 branch. I'll release the next (and final) beta this week, probably. I recommend giving it a try. (A word of caution though, there are some protocol changes and beta3 will not be compatible with beta2.)

The new system can handle server crashes without losing session content, correctly stores all session attributes, automatically re-announces the session if the server is restarted, and can be configured to just rename session files instead of deleting them.

**Comment by jameslis** [comment]
Thanks for the heads up, we'll look out for beta 3 then and do a bit of testing on there. 

Quick question, is it able to flush a session to disk on demand (via chat command or timer)? As far as I can tell this only happens when the server is shut down in 1.0.6 anyways.

**Comment by callaa** [comment]
In 1.0.6, the session is written to disk only on server shutdown. In 2.0, (when the feature is enabled) session history is continuously written to disk and only parts of the file are cached in RAM. This way, even if the server crashes, the session is not lost.

**Comment by jameslis** [comment]
That's perfect, can't wait to try it out!
