### ISSUE TITLE
Request - arrow instead of a crosshair

### ISSUE THREAD

**Issue by szkielethor** [callaa/Drawpile#396]
Crosshair somewhat obscures view. Pen-like arrow within a few pixels would be better. Like this:
http://i.imgur.com/iDULcGT.png
Besides, when I record an educational video in 720p or 1080p, thin crosshair is poorly visible to the viewer:
https://www.youtube.com/watch?v=ALMMK5LP60o
I would be in seventh heaven, if I had to choose between crosshair and arrow.

**Comment by callaa** [comment]
You can switch off the crosshair cursor from the View menu, but I'll try how how a pen cursor like in your example would look.

**Comment by szkielethor** [comment]
Yes, I know I can switch it off. Without it the view is not obstructed, but it's hard to see where the cursor is at all.

**Comment by callaa** [comment]
![brush-cursor-mockup](https://cloud.githubusercontent.com/assets/464576/22746068/5a4d4a66-ee2b-11e6-83c9-615097ab1ccb.png)

Here's a mockup of how the new cursors might look. There's a single white pixel that indicates the cursor hotspot so the brush center can still be found, even when the outline is not visible.

Since the invisible outline problem was the only reason for having the crosshair cursor, I think these new brush specific cursors could replace it altogether. What do you think?

**Comment by szkielethor** [comment]
Wow, you treat this project really seriously! 
First of all: you shouldn't rely so much on my opinion, because I don't belong sctrictly to your target group. It is so, because I use Drawpile primarily for online lessons and making educational videos for YouTube, not so often for drawing). So, to avoid confusion, from now on I'll write as if I was 100% teacher, 0% painter.

All I want is more noticeable position of the cursor, while not overshadowing stuff beneath . Take a look at this:
![image](https://cloud.githubusercontent.com/assets/13998536/22785969/c4c893cc-eed6-11e6-8761-b321acfe8139.png)
In video I'm talking about red vector and I'm pointing at it, but it's hard to see what I'm pointing at. 
Or this one:
![image](https://cloud.githubusercontent.com/assets/13998536/22786011/07d19fa6-eed7-11e6-80c3-b9a83c7b2bba.png)
I'm pointing at the formula with crosshair and making it less readable by doing so. (I know there's a big arrow in laser pointer, but I tend to forget to switch to it.) 
A simple arrow instead of a crosshair would do for me. Something like pen on your mockup or like cursor on screenshots above. Brush from your mockup can be confusing in education, since it point the other way. I'm using brush for my lessons, because it looks nice.

And as for your question:
I think brush specific cursor would be nice for painters, it's good to see what tool are you holding.
Single white dot... Hmm... Seems OK. As long as the background isn't white. A white dot with few black pixels around would be better perhaps.

Circle in your mockup: it's to indicate pen/brush size as it is now, right?

**Comment by blurymind** [comment]
@szkielethor If I remember right drawpile had a laser tool - specifically designed for pointing :)

**Comment by callaa** [comment]
While Drawpile's primary focus is indeed drawing, I try to accommodate other use cases as well. This brush cursor redesign has been long overdue, I think.
Here's a second mockup:

![brush-cursor-mockup2](https://cloud.githubusercontent.com/assets/464576/22794056/6d27d186-eefa-11e6-808e-80acd2779510.png)

I noticed Krita uses a magenta brush outline that, like the one in Drawpile, is XORed with the canvas color. This is a much better color choice than the full white/black Drawpile uses, since it will show up with adequate contrast on pretty much any color.

In the updated mockup, I moved the hotspot to the bottom of the cursor, so the brush tip points at it. I also removed the white pixel, since it is no longer needed with the better outline color.

**Comment by szkielethor** [comment]
Now your idea seems to be better than GIMP:
![image](https://cloud.githubusercontent.com/assets/13998536/22805032/f4ed31bc-ef1b-11e6-813b-4b91b0ed247c.png)
It is as good as GIMP for me as an online teacher and  - IMHO - even better for painters, because GIMP's arrow sometimes obscures view (especially when working with small details). Don't know if 100% painters would agree. Query on facebook seems like a good idea before changing crucial UI elements.

As you can see on my screenshot some programs have cursors pointing from top right (like your mockup) and some from bottom right (like GIMP). For me the latter is more natural. I quess it's the matter of taste. Or the matter of watching Windows cursor:
![image](https://cloud.githubusercontent.com/assets/13998536/22805530/47ca5458-ef1e-11e6-84b8-c5271ff37594.png)
XORing with canvas - excellent:)

**Comment by jane-fox** [comment]
Just my two cents - the XOR for contrast is great, but I also liked the little 1 pixel dot in the center of the circle. While drawing with pressure sensitivity it might help with accuracy.

**Comment by callaa** [comment]
I agree the bottom-right cursors feel more natural. After trying out a few more combinations, I settled on making most of the cursors bottom-right oriented. (The brush cursor is still top-right, because I think it looks better that way.) I also took jane-foxes advice and added the white pixel back. It is indeed quite nice to have, even with the more contrasty outline.

These changes will appear in the next release, which will be the 2.0.0 release candidate, due out in a couple of weeks perhaps.

**Comment by callaa** [comment]
The new cursors have met some rather vocal disapproval. So, I'll remove them for the 2.0.0 release (I'll leave the white dot in, though) and in version 2.0.1, I'll add an option to select between the minimal cursor, a crosshair or the regular arrow pointer.

**Comment by bart-aleks** [comment]
I see. To tell the truth it was awkward for me to use those new cursors. I managed to adjust to them after a few hours, but it was hard. Too hard for many, I quess, and it's hard to blame them. I didn't expect it would do such a big diffrence, really sorry for pointing you to a wrong direction.
To give users a choice between pointers is really good idea. A GIMP-like arrow pointer is not so bad. Please consider to give users even more choice in future versions. For example choice between: "normal arrow", "small arrow" and "big arrow". (GIMP arrow seems to be a bit to small for recording my 1080p physics tutorials.) 
Seems like nobody likes pointer moved away a few pixels and I'm the only one who need it. So f*ck me. But hey, I can modify source code locally and compile my own Drawpile, right? Or is it against some copyright law?

**Comment by callaa** [comment]
Sure, the license allows you to modify the code and even distribute your modified version too.

There are two places in the code where you can change the cursor:

[CanvasView constructor](https://github.com/drawpile/Drawpile/blob/c828418ca13597a6eb379c074e831773f79979fc/src/desktop/scene/canvasview.cpp#L78): here you can replace the dot cursor used for brushes

[CanvasView::resetCursor](https://github.com/drawpile/Drawpile/blob/c828418ca13597a6eb379c074e831773f79979fc/src/desktop/scene/canvasview.cpp#L192): this is where the active cursor is actually set. Later, I'll replace the dotcursor variable with a configurable custom brush cursor.

**Comment by bart-aleks** [comment]
Thank you! You're the best!
